# Generated by Django 5.1.4 on 2025-03-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0004_alter_treasure_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
