# Generated by Django 5.1.4 on 2025-03-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0005_alter_treasure_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
