# Generated by Django 5.1.4 on 2025-03-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0006_alter_treasure_category_alter_treasure_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treasure',
            options={'ordering': ['creator', 'id']},
        ),
    ]
