# Generated by Django 5.1.4 on 2025-01-07 21:07

import comments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treasures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=models.SET(comments.models.unknown_author), to=settings.AUTH_USER_MODEL)),
                ('treasure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasures.treasure')),
            ],
        ),
    ]
