# Generated by Django 5.1.4 on 2025-01-09 10:03

import comments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('treasures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(comments.models.unknown_author), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='treasure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasures.treasure'),
        ),
    ]
