# Generated by Django 5.1.4 on 2025-01-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='handle',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='handle'),
        ),
    ]
