# Generated by Django 5.1.4 on 2025-02-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='last_modified',
        ),
    ]
