# Generated by Django 5.1.4 on 2025-06-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='handle'),
        ),
    ]
