# Generated by Django 5.1.4 on 2025-03-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_emailaddress_unique_primary_email'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comments', '0004_remove_comment_last_modified'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        ('treasures', '0004_alter_treasure_category'),
        ('users', '0003_alter_customuser_handle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
