# Generated by Django 5.1.4 on 2025-01-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
