# Generated by Django 5.1.4 on 2025-01-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0003_alter_treasure_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
